FROM pytorch/pytorch:1.9.0-cuda11.1-cudnn8-devel
RUN apt-update && apt-get install -y libglib2.0-dev libgl1-mesa-glx
COPY ./requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt