FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-devel
RUN apt-get update && apt-get install -y libglib2.0-dev libgl1-mesa-glx
COPY ./requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
RUN pip install --no-cache-dir jupyter jupyterlab